services:
  ray-head:
    build: .
    command: >
      bash -c "ray start --head --port=6379 --dashboard-host 0.0.0.0 && tail -f /dev/null"
    ports:
      - "8265:8265"   # Ray Dashboard
      - "6380:6379"   # Change external port to 6380, while internal remains 6379 for Ray
    volumes:
      - ./app:/app    # Optional: Mount your app directory
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ray-network

  ray-worker:
    build: .
    command: >
      bash -c "ray start --address='ray-head:6379' && tail -f /dev/null"
    depends_on:
      - ray-head
    volumes:
      - ./app:/app    # Optional: Mount your app directory
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ray-network
    deploy:
      replicas: 2  # Number of worker nodes

networks:
  ray-network:
    driver: bridge
