apiVersion: v1
kind: Pod
metadata:
  name: recommendations-pod
  labels:
    ml: pytorch
spec:
  containers:
    - name: recommendation-service
      image: recommendations:latest
      imagePullPolicy: Never
